#pragma once

#include <classes/rtti.h>

#include <classes/AccountCharacterData.h>
#include <classes/PingPongFrameStrategy.h>
#include <classes/LoopFrameStrategy.h>
#include <classes/NextFrameStrategy.h>
#include <classes/LenshelpWindow.h>
#include <classes/GUIContextMenuAction.h>
#include <classes/GUIContextMenu.h>
#include <classes/ObjectContextMenu.h>
#include <classes/ConsoleContextMenu.h>
#include <classes/ConsoleTabContextMenu.h>
#include <classes/AttackContextMenu.h>
#include <classes/BuddylistContextMenu.h>
#include <classes/EditContextMenu.h>
#include <classes/AutomapContextMenu.h>
#include <classes/SkillsContextMenu.h>
#include <classes/WaresListContextMenu.h>
#include <classes/SingletonI21TContainerViewManagerE.h>
#include <classes/ContainerViewManager.h>
#include <classes/MessageStorage.h>
#include <classes/SingletonI15TMessageStorageE.h>
#include <classes/SingletonI17TInventoryStorageE.h>
#include <classes/InventoryStorage.h>
#include <classes/GUITextWindow.h>
#include <classes/ConsoleTextWindow.h>
#include <classes/ConsoleTab.h>
#include <classes/ConsoleTabWindow.h>
#include <classes/CooldownBarWindow.h>
#include <classes/ConsoleWindow.h>
#include <classes/GUIDecorateLine.h>
#include <classes/GUIResizer.h>
#include <classes/GUIFrameWindow.h>
#include <classes/GUIWrappingTextRectangle.h>
#include <classes/GUITextRectangle.h>
#include <classes/GUIFormatTextRectangle.h>
#include <classes/GUISpriteResizer.h>
#include <classes/GUIObjectDisplay.h>
#include <classes/GUICreatureDisplay.h>
#include <classes/GUISkinDisplay.h>
#include <classes/GUITutorialHintImageDisplay.h>
#include <classes/GUIButton.h>
#include <classes/GUIColoredButton.h>
#include <classes/GUITextureButton.h>
#include <classes/GUIFlashButton.h>
#include <classes/GUITextButton.h>
#include <classes/GUICheckButton.h>
#include <classes/GUITextCheckButton.h>
#include <classes/GUIRotateButton.h>
#include <classes/GUILink.h>
#include <classes/GUICheckbox.h>
#include <classes/GUISlider.h>
#include <classes/GUIButtonSlider.h>
#include <classes/GUIScrollbar.h>
#include <classes/GUIButtonScrollbar.h>
#include <classes/GUIEdit.h>
#include <classes/GUIPasswordEdit.h>
#include <classes/GUIEditArea.h>
#include <classes/GUIListbox.h>
#include <classes/GUIProgressbar.h>
#include <classes/DialogWindow.h>
#include <classes/SimpleContentWindow.h>
#include <classes/ContentWindow.h>
#include <classes/GenericContentWindow.h>
#include <classes/GUIComponent.h>
#include <classes/GUIComposite.h>
#include <classes/GUIElement.h>
#include <classes/ObjectTimer.h>
#include <classes/MainFrameLin.h>
#include <classes/MainWindow.h>
#include <classes/TitleWindow.h>
#include <classes/SeparatorBar.h>
#include <classes/GUIContentBody.h>
#include <classes/UnjustPointsWindow.h>
#include <classes/MapFrame.h>
#include <classes/MapWindow.h>
#include <classes/PlayerSocket.h>
#include <classes/Stopwatch.h>
#include <classes/StopwatchBase.h>
#include <classes/PlayerAppLin.h>
#include <classes/SingletonI15TPremiumManagerE.h>
#include <classes/PremiumManager.h>
#include <classes/Report.h>
#include <classes/NameReport.h>
#include <classes/StatementReport.h>
#include <classes/BotReport.h>
#include <classes/Surface.h>
#include <classes/SurfaceGL.h>
#include <classes/TextBuffer.h>
#include <classes/TextBufferNPCsChannel.h>
#include <classes/TextBufferAddressee.h>
#include <classes/TextBufferChannel.h>
#include <classes/TextBufferPrivateChatChannel.h>
#include <classes/MyException.h>
#include <classes/RandomNumberGenerator.h>
#include <classes/XTEASymmetricKey.h>
#include <classes/MessageQueue.h>
#include <classes/BuddyData.h>
#include <classes/HostData.h>
#include <classes/AttackWindow.h>
#include <classes/AutomapWindow.h>
#include <classes/AutomapDisplay.h>
#include <classes/AutomapRose.h>
#include <classes/BuddylistWindow.h>
#include <classes/ButtonWindow.h>
#include <classes/CombatButtonWindow.h>
#include <classes/ContainerWindow.h>
#include <classes/ContainerWindow14TWindowContentE.h>
#include <classes/ContainerWindow13TWindowFooterE.h>
#include <classes/Capacity.h>
#include <classes/Soulpoints.h>
#include <classes/BlessingIcon.h>
#include <classes/PlayerStates.h>
#include <classes/InventoryWindow.h>
#include <classes/SmallInventoryWindow.h>
#include <classes/PurseButton.h>
#include <classes/MiniPremiumButton.h>
#include <classes/BigInventoryWindow.h>
#include <classes/PremiumButtonWindow.h>
#include <classes/PremiumWindowBody.h>
#include <classes/PremiumWindow.h>
#include <classes/SkillsWindow.h>
#include <classes/StatusWindow.h>
#include <classes/TradePreviewWindow.h>
#include <classes/TradeNamesWindow.h>
#include <classes/TradeAcceptWindow.h>
#include <classes/TradeWindow.h>
#include <classes/NPCTradeBuySellWindow.h>
#include <classes/NPCTradeWaresWindow.h>
#include <classes/NPCTradeDealWindow.h>
#include <classes/NPCTradeWindow.h>
#include <classes/UnjustPointsBar.h>
#include <classes/UnjustPointsWindowBody.h>
#include <classes/AddBuddyDialog.h>
#include <classes/EditBuddyDialog.h>
#include <classes/BugreportDialog.h>
#include <classes/ChannelDialog.h>
#include <classes/ChannelInvitationDialog.h>
#include <classes/SimpleEditTextDialog.h>
#include <classes/EditListDialog.h>
#include <classes/EditAutomapFlagDialog.h>
#include <classes/EditTextDialog.h>
#include <classes/EnterGameDialog.h>
#include <classes/SelectCharacterDialog.h>
#include <classes/DownloadDialog.h>
#include <classes/ExitDialog.h>
#include <classes/GUIModalDialog.h>
#include <classes/YesNoDialog.h>
#include <classes/EnterTextDialog.h>
#include <classes/GUIServerModalDialog.h>
#include <classes/ErrorFileEntryDialog.h>
#include <classes/ExportDataSuccessfulDialog.h>
#include <classes/HelpMenu.h>
#include <classes/IgnoreListDialog.h>
#include <classes/MarketBrowseOffersDialog.h>
#include <classes/MarketOwnOffersDialog.h>
#include <classes/MoveObjectsDialog.h>
#include <classes/OptionsMenu.h>
#include <classes/GeneralOptionsDialog.h>
#include <classes/GraphicsOptionsDialog.h>
#include <classes/AdvancedGraphicsOptionsDialog.h>
#include <classes/ConsoleOptionsDialog.h>
#include <classes/HotkeyOptionsDialog.h>
#include <classes/CloneHotkeyPresetDialog.h>
#include <classes/RemoveHotkeyPresetDialog.h>
#include <classes/GUIPresetListbox.h>
#include <classes/QuestLogDialog.h>
#include <classes/QuestLineDialog.h>
#include <classes/ReportStep1Dialog.h>
#include <classes/ReportStep2Dialog.h>
#include <classes/ReportStep3Dialog.h>
#include <classes/SelectOutfitDialog.h>
#include <classes/SurveyInvitationDialog.h>
#include <classes/TutorialHintMenuDialog.h>
#include <classes/TutorialHintDialog.h>
#include <classes/WaitDialog.h>
#include <classes/LoginQueueWaitDialog.h>
